"""Babylon WebGPU startup and automatic WebGL fallback integration."""
import argparse
import sys
import threading
from http.server import HTTPServer
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import server
from playwright.sync_api import sync_playwright


class QuietHandler(server.Handler):
    """Serve browser fixtures without expected test-traffic noise."""
    def log_message(self, *_args):
        """Suppress access logs generated by Playwright."""
        pass

    def handle(self):
        """Ignore clients closing optional asset requests during teardown."""
        try:
            super().handle()
        except BrokenPipeError:
            pass


def accept_session(page, base, query=''):
    """Wait for GPU convergence, accept cookies, and await renderer startup."""
    page.goto(base + '/' + query)
    page.wait_for_selector('#welcome[open]')
    page.wait_for_function("['pass','fail'].includes(document.documentElement.dataset.gpuTest)")
    assert page.locator('#gpu-status').get_attribute('class') != 'gpu-status checking'
    page.locator('#welcome-name').fill('Renderer Tester')
    page.locator('#cookie-consent').check()
    page.locator('#welcome-form button').click()
    page.wait_for_function(
        "document.documentElement.dataset.renderer && "
        "!document.body.classList.contains('busy')"
    )
    if 'mode=single' in query:
        page.wait_for_selector('#preparation[open]')


parser = argparse.ArgumentParser()
parser.add_argument('--headed', action='store_true')
args = parser.parse_args()

server.registry = server.SessionRegistry()
httpd = HTTPServer(('127.0.0.1', 0), QuietHandler)
threading.Thread(target=httpd.serve_forever, daemon=True).start()
base = f'http://127.0.0.1:{httpd.server_port}'

try:
    with sync_playwright() as playwright:
        webgpu = playwright.chromium.launch(
            channel='chromium',
            headless=not args.headed,
            args=[
                '--no-sandbox',
                '--use-angle=vulkan',
                '--enable-features=Vulkan',
                '--disable-vulkan-surface',
                '--enable-unsafe-webgpu',
            ],
        )
        page = webgpu.new_page(viewport={'width': 1440, 'height': 1000})
        page.set_default_timeout(60000)
        errors = []
        page.on('pageerror', lambda error: errors.append(str(error)))
        accept_session(page, base, '?mode=single')
        result = page.evaluate("""async () => {
            const {battlefield} = await import('/app.js');
            return {
                renderer: battlefield.renderer,
                gpuTest: document.documentElement.dataset.gpuTest,
                webgpu: battlefield.engine instanceof BABYLON.WebGPUEngine,
                meshes: battlefield.nativeScene.meshes.length,
                quality: Boolean(battlefield.qualityPipeline),
                generatedStone: battlefield.concreteMat.native.albedoTexture.url,
                status: document.querySelector('#gpu-status').className,
                target: document.querySelector('#gpu-status').getAttribute('href'),
            };
        }""")
        assert result['renderer'] == 'webgpu', result
        assert result['gpuTest'] == 'pass', result
        assert result['webgpu'] and result['meshes'] > 100, result
        assert result['quality'], result
        assert result['generatedStone'].endswith('/assets/limestone-webgpu-v1.png'), result
        assert result['status'] == 'gpu-status available', result
        assert result['target'] == '/gpu-test', result
        tree = page.evaluate('''async () => {
            const {battlefield}=await import('/app.js');
            const {addProp}=await import('/environment.js');
            const group=addProp(battlefield,{id:'detail-tree-test',kind:'tree_oak',x:-5,y:-5,width:1,depth:1,hp:100,max_hp:100,variant:2});
            const branch=group.native.getChildMeshes().find(m=>m.name==='tree-branches');
            const owner=branch?.metadata?.pickOwner;
            return {pickable:branch?.isPickable,structure:owner?.userData.structure,
                registered:battlefield.pickables.includes(owner),
                healthLabel:battlefield.pickables.some(o=>o!==owner&&o.userData.structure==='detail-tree-test')};
        }''')
        assert tree == {'pickable':True,'structure':'detail-tree-test','registered':True,'healthLabel':True}, tree
        assert not errors, errors
        page.close()
        diagnostic = webgpu.new_page()
        diagnostic.goto(base + '/gpu-test')
        diagnostic.wait_for_selector('#summary.pass')
        assert diagnostic.locator('#details').is_visible()
        webgpu.close()
        print('PASS WebGPU: Babylon engine, scene assets, and landing GPU status.')

        fallback = playwright.chromium.launch(
            channel='chromium',
            headless=not args.headed,
            args=[
                '--no-sandbox',
                '--use-gl=angle',
                '--use-angle=swiftshader',
                '--disable-features=WebGPU',
                '--enable-unsafe-swiftshader',
            ],
        )
        page = fallback.new_page(viewport={'width': 1440, 'height': 1000})
        page.set_default_timeout(60000)
        errors = []
        page.on('pageerror', lambda error: errors.append(str(error)))
        accept_session(page, base)
        result = page.evaluate("""async () => {
            const {battlefield} = await import('/app.js');
            return {
                renderer: battlefield.renderer,
                gpuTest: document.documentElement.dataset.gpuTest,
                webgl: battlefield.engine instanceof BABYLON.Engine,
                quality: Boolean(battlefield.qualityPipeline),
                generatedStone: battlefield.concreteMat.native.albedoTexture.url,
                status: document.querySelector('#gpu-status').className,
            };
        }""")
        assert result == {
            'renderer': 'webgl',
            'gpuTest': 'fail',
            'webgl': True,
            'quality': False,
            'generatedStone': '/assets/concrete-weathered-v2.webp',
            'status': 'gpu-status fallback',
        }, result
        assert not errors, errors
        fallback.close()
        print('PASS WebGL fallback: compatibility renderer and landing status.')
finally:
    httpd.shutdown()
    httpd.server_close()
